runtime: nodejs18
instance_class: F1

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_instances: 3

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

includes:
 - environ.yaml
