name: Deploy

on:
  push:
    branches:
      - main
      - v2-develop

jobs:
  backend-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.31.0

    - name: Create environ.yaml
      run: deno run --allow-write=. .github/createEnviron.ts \
            --NEXT_PUBLIC_API_URL https://api.mikage.click/v1 \
            --NEXT_PUBLIC_MONOCRAFT_VOTE_URL https://monocraft.net/servers/tRkOlmkTq0r0lOX4Ir9c/vote \
            ${{ secrets.JWT_SECRET }}

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        deliverables: app.yaml
